### ISSUE TITLE
Prepare app for deployment 

### ISSUE THREAD

**Issue by molly-clabots** [molly-clabotst/lmnop#2]
Replace database with production database; enable app to use local or production database automatically, depending on where it is running
Configuration etc. for GCP
Deploy ASAP; deploy updates and new features as soon as they are ready (like they work and have tests)

**Comment by molly-clabots** [comment]
GCP = Google Cloud Platform
Examples in for dependency switching in Vehicle program

**Comment by Di30an** [comment]
App is deployed, pending pull request. Attached is a link to deployed app. 

https://lmnop-273410.appspot.com/accounts/login/?next=/venues/list/
